// <auto-generated />
using BreadOven.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BreadOven.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20250205111840_updatevlauetodecimal")]
    partial class updatevlauetodecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BreadOven.Models.ProductionLineDepreciation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductionAgeYear")
                        .HasColumnType("int");

                    b.Property<string>("ValuePercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("valueDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valueHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valueMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("valueYear")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductionLineDepreciations");
                });
#pragma warning restore 612, 618
        }
    }
}
